name: "general"
windows:
  - name: site
    root: ~/src/gsong/personal-site/
    layout: even-vertical
    panes:
      - focus: true
      - commands:
          - git fetch
          - pnpm install
          - pnpm run dev
      - claude --mcp-debug
