[language_servers.pylsp]
enable_ruff = true
enable_mypy = true
enable_pydocstyle = false
enable_pyflakes = false
enabled = true
enable_pylint = false
enable_flake8 = false

[formatting]
line_length = 79

[runtime]
dotenv = []
reactive_tests = true
std_stream_max_bytes = 1000000
auto_instantiate = true
on_cell_change = "autorun"
output_max_bytes = 8000000
auto_reload = "lazy"
watcher_on_save = "lazy"

[ai]
rules = ""
[ai.anthropic]

[ai.google]

[ai.open_ai]

[completion]
activate_on_typing = true
copilot = "github"

[experimental]
lsp = true

[display]
code_editor_font_size = 14
cell_output = "above"
dataframes = "rich"
default_width = "full"
theme = "system"

[package_management]
manager = "uv"

[diagnostics]
enabled = true

[keymap]
preset = "vim"
[keymap.overrides]

[server]
follow_symlink = false
browser = "default"

[save]
autosave_delay = 5000
autosave = "after_delay"
format_on_save = true

[snippets]
include_default_snippets = true
custom_paths = []
